import { SkillIsland, SkillCategory } from "./types";

export const skillIslands: SkillIsland[] = [
  // Core Islands (Large, Prominent)
  {
    id: 1,
    name: "React",
    category: "Frontend",
    proficiency: 95,
    color: "#61DAFB",
    size: 120,
    x: 50,
    y: 50,
    height: 180,
    theme: "tropical",
    description:
      "Advanced React with hooks, context, and performance optimization",
    shape: "organic",
    connections: [2, 3, 4],
  },
  {
    id: 2,
    name: "Node.js",
    category: "Backend",
    proficiency: 92,
    color: "#339933",
    size: 110,
    x: 25,
    y: 35,
    height: 160,
    theme: "forest",
    description: "Server-side JavaScript with Express and middleware",
    shape: "mountain",
    connections: [1, 5, 6],
  },
  {
    id: 3,
    name: "TypeScript",
    category: "Frontend",
    proficiency: 90,
    color: "#3178C6",
    size: 100,
    x: 75,
    y: 35,
    height: 150,
    theme: "arctic",
    description: "Strong typing and advanced TypeScript patterns",
    shape: "crystal",
    connections: [1, 4, 7],
  },

  // Supporting Islands (Medium)
  {
    id: 4,
    name: "Next.js",
    category: "Frontend",
    proficiency: 88,
    color: "#000000",
    size: 90,
    x: 85,
    y: 60,
    height: 130,
    theme: "modern",
    description: "Full-stack React framework with SSR and SSG",
    shape: "geometric",
    connections: [1, 3],
  },
  {
    id: 5,
    name: "PostgreSQL",
    category: "Database",
    proficiency: 88,
    color: "#336791",
    size: 95,
    x: 15,
    y: 70,
    height: 140,
    theme: "crystal",
    description: "Advanced SQL queries and database optimization",
    shape: "geometric",
    connections: [2, 6],
  },
  {
    id: 6,
    name: "Docker",
    category: "Tools",
    proficiency: 85,
    color: "#2496ED",
    size: 85,
    x: 35,
    y: 80,
    height: 120,
    theme: "ocean",
    description: "Containerization and microservices architecture",
    shape: "organic",
    connections: [2, 5],
  },

  // Smaller Islands
  {
    id: 7,
    name: "Vue.js",
    category: "Frontend",
    proficiency: 85,
    color: "#4FC08D",
    size: 80,
    x: 65,
    y: 75,
    height: 110,
    theme: "zen",
    description: "Vue 3 with Composition API and ecosystem",
    shape: "organic",
    connections: [3],
  },
  {
    id: 8,
    name: "Laravel",
    category: "Backend",
    proficiency: 80,
    color: "#FF2D20",
    size: 75,
    x: 45,
    y: 85,
    height: 100,
    theme: "desert",
    description: "PHP framework with Eloquent ORM and Blade",
    shape: "organic",
    connections: [2],
  },
  {
    id: 9,
    name: "MongoDB",
    category: "Database",
    proficiency: 82,
    color: "#47A248",
    size: 80,
    x: 75,
    y: 85,
    height: 115,
    theme: "jungle",
    description: "NoSQL database with aggregation pipelines",
    shape: "organic",
    connections: [2],
  },
  {
    id: 10,
    name: "Git",
    category: "Tools",
    proficiency: 90,
    color: "#F05032",
    size: 90,
    x: 50,
    y: 20,
    height: 145,
    theme: "mountain",
    description: "Version control and collaborative development",
    shape: "mountain",
    connections: [1, 2],
  },
  {
    id: 11,
    name: "AWS",
    category: "Tools",
    proficiency: 78,
    color: "#FF9900",
    size: 70,
    x: 20,
    y: 50,
    height: 95,
    theme: "storm",
    description: "Cloud infrastructure and serverless architecture",
    shape: "organic",
    connections: [2, 6],
  },
  {
    id: 12,
    name: "GraphQL",
    category: "Backend",
    proficiency: 85,
    color: "#E10098",
    size: 75,
    x: 80,
    y: 45,
    height: 105,
    theme: "neon",
    description: "Query language and runtime for APIs",
    shape: "geometric",
    connections: [1, 2],
  },
];

export const skillCategories: SkillCategory[] = [
  { name: "Frontend", color: "#61DAFB", icon: "🌊" },
  { name: "Backend", color: "#339933", icon: "🏔️" },
  { name: "Database", color: "#336791", icon: "💎" },
  { name: "Tools", color: "#2496ED", icon: "⚡" },
];

// Organic shape paths for skill islands
export const organicShapes = {
  organic:
    "polygon(50% 0%, 83% 12%, 100% 43%, 94% 78%, 68% 100%, 32% 100%, 6% 78%, 0% 43%, 17% 12%)",
  mountain: "polygon(50% 0%, 0% 100%, 25% 85%, 50% 100%, 75% 85%, 100% 100%)",
  crystal: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
  geometric: "polygon(25% 0%, 75% 0%, 100% 50%, 75% 100%, 25% 100%, 0% 50%)",
};

// Skill proficiency levels
export const proficiencyLevels = {
  expert: {
    range: [90, 100],
    label: "Expert",
    color: "#10B981",
    icon: "🔥",
  },
  advanced: {
    range: [80, 89],
    label: "Advanced",
    color: "#3B82F6",
    icon: "⚡",
  },
  intermediate: {
    range: [70, 79],
    label: "Intermediate",
    color: "#F59E0B",
    icon: "🚀",
  },
  beginner: {
    range: [60, 69],
    label: "Beginner",
    color: "#EF4444",
    icon: "🌱",
  },
};

// Skills section configuration
export const skillsConfig = {
  title: "Skills & Technologies",
  subtitle: "My technical expertise across different domains",
  waterEffect: {
    waveCount: 15,
    animationDuration: "20s",
    opacity: "opacity-30",
  },
  islandInteraction: {
    hoverScale: "scale-125",
    transitionDuration: "duration-300",
    glowEffect: "shadow-blue-400/25",
  },
};

// Skill themes for visual variety
export const skillThemes = {
  tropical: {
    name: "Tropical",
    gradient: "from-green-400 to-blue-400",
    accent: "#10B981",
  },
  forest: {
    name: "Forest",
    gradient: "from-green-600 to-emerald-600",
    accent: "#059669",
  },
  arctic: {
    name: "Arctic",
    gradient: "from-blue-400 to-cyan-400",
    accent: "#06B6D4",
  },
  modern: {
    name: "Modern",
    gradient: "from-gray-600 to-gray-800",
    accent: "#6B7280",
  },
  crystal: {
    name: "Crystal",
    gradient: "from-purple-400 to-pink-400",
    accent: "#EC4899",
  },
  ocean: {
    name: "Ocean",
    gradient: "from-blue-500 to-indigo-500",
    accent: "#6366F1",
  },
  zen: {
    name: "Zen",
    gradient: "from-green-300 to-teal-300",
    accent: "#14B8A6",
  },
  desert: {
    name: "Desert",
    gradient: "from-orange-400 to-red-400",
    accent: "#F97316",
  },
  jungle: {
    name: "Jungle",
    gradient: "from-green-500 to-lime-500",
    accent: "#84CC16",
  },
  mountain: {
    name: "Mountain",
    gradient: "from-gray-500 to-gray-700",
    accent: "#6B7280",
  },
  storm: {
    name: "Storm",
    gradient: "from-gray-600 to-blue-600",
    accent: "#2563EB",
  },
  neon: {
    name: "Neon",
    gradient: "from-pink-500 to-purple-500",
    accent: "#A855F7",
  },
};
